/** These constants represent the Google Datastore kinds that are used across
 * the API server. */
export const kinds = {
  /** An object which contains information about the usage of built-in APIs. */
  API_STATS_KIND: "api_stats",
  /** A cached version of the meta data associated with a code page view. */
  CODE_PAGE_KIND: "code_page",
  /** A single entity which holds configuration, specifically related to API
   * token authentication. */
  CONFIG_KIND: "config",
  /** An error that was generated when doing the dependency analysis of a
   * module. */
  DEP_ERROR_KIND: "dependency_error",
  /** A cache of information about each dependency source. */
  DEP_METRICS_KIND: "dependency_metrics",
  /** A representation of a doc node generated by `deno_doc` which has been
   * serialized to an entity which can be stored in the Google Datastore. */
  DOC_NODE_KIND: "doc_node",
  /** Cached version of the meta data related to a documentation page. */
  DOC_PAGE_KIND: "doc_page",
  /** A doc work item, which indicates a module that needs to be doc'ed. */
  DOC_WORK_ITEM: "doc_work_item",
  /** Cached information about global symbols that are available in Deno CLI. */
  GLOBAL_SYMBOLS_KIND: "global_symbols",
  /** Cached version of the meta data for an info page of a module. */
  INFO_PAGE_KIND: "info_page",
  /** Meta data about a library (e.g. Deno Stable). */
  LIBRARY_KIND: "library",
  /** Meta data associated with a specific version of a library. */
  LIBRARY_VERSION_KIND: "library_version",
  /** Daily and version related usage for a module. */
  METRIC_USAGE_KIND: "metric_usage",
  /** A dependency of a module. */
  MODULE_DEP_KIND: "module_dependency",
  /** A file or directory that is associated with a specific module version, along
   * with other meta data associated with that entry. */
  MODULE_ENTRY_KIND: "module_entry",
  /** A cache of the index of a directory within a module */
  MODULE_INDEX_KIND: "module_index",
  /** The meta data associated with a module. */
  MODULE_KIND: "module",
  /** Metrics for modules.  */
  MODULE_METRICS_KIND: "module_metrics",
  /** Meta data related to a specific version of a module.  */
  MODULE_VERSION_KIND: "module_version",
  /** A cached version of the navigation index for a module dir. */
  NAV_INDEX_KIND: "nav_index",
  /** A cached version of an index of paths used for generating completions. */
  PATH_COMPLETIONS_KIND: "path_completions",
  /** Represents dependency metric information by source type. */
  SOURCE_METRIC_KIND: "dependency_metrics",
  /** Metrics for a submodule. */
  SUBMODULE_METRICS_KIND: "submodule_metrics",
  /** A cache of symbols within the scope of a module. */
  SYMBOL_INDEX_KIND: "symbol_index",
  /** A cache of symbol items for libraries. */
  SYMBOL_ITEMS_KIND: "symbol_items",

  BUILD_KIND: "build",
} as const;
